ACMS-3508: Update config.settings.php with drs override config dir.
acquia/drupal-recommended-settings pull request #31
Opened 2024-01-18 16:25 UTC by apathak18

**Motivation**

Fixes ACMS-3508

**Proposed changes**
Adding logic of drs override config directories for site studio and config management.

2024-01-22 05:23 UTC, chandan-singh7929 commented on settings/config.settings.php
> +  $settings['config_sync_directory'] = "../config/" . $site_name;
@apathak18 - This will follow the similar logic what you have done at line 24-26, also keep the variable separate in respective if condition block.

2024-01-24 08:01 UTC, rajeshreeputra requested changes
Overall changes looks good.

2024-01-24 08:01 UTC, rajeshreeputra commented on settings/config.settings.php
> +"../sitestudio/$site_name" : "../sitestudio/default";
As per my knowledge with Ternary Operator first is true then false. Here if the $drs_override_site_studio_sync_directories is true then config will be exported in "../sitestudio/default" else in "../sitestudio/$site_name", right?
```suggestion
$settings['site_studio_sync'] = $drs_override_site_studio_sync_directories ?
"../sitestudio/default" : "../sitestudio/$site_name";
```

2024-01-31 08:29 UTC, vishalkhode1 approved these changes

2024-01-31 09:32 UTC, merged